2018-06-14 14:47:50,587 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:36]
2018-06-14 14:48:03,431 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:36]
2018-06-14 14:51:09,671 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:36]
2018-06-14 14:56:06,786 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:36]
2018-06-15 08:50:33,886 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-15 08:50:55,515 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-15 08:51:05,271 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-15 08:51:08,921 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-15 08:51:19,729 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-15 15:04:41,628 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 12:37:02,641 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:41]
2018-06-18 12:37:58,645 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:41]
2018-06-18 12:39:45,342 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:41]
2018-06-18 12:47:17,309 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:41]
2018-06-18 12:47:27,011 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:41]
2018-06-18 12:47:59,394 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 12:48:31,264 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 12:48:45,248 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 12:48:49,013 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 12:48:55,039 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:14:59,803 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:15:20,437 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:18:57,478 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:23:23,352 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:28:45,594 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:29:37,295 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:29:43,395 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:29:51,489 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:34:31,370 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:34:41,671 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:34:47,695 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:36:11,887 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:36:25,908 ERROR: Exception on /subscribe [POST] [in c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cmarsh\YewzOfficial\app\routes.py", line 22, in subscribe
    if form.validate() == False:
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
TypeError: 'Email' object is not callable
2018-06-18 14:41:37,041 ERROR: Exception on /subscribe [POST] [in c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cmarsh\YewzOfficial\app\routes.py", line 22, in subscribe
    email_addr = Email(email_addr=form.email_addr.data)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
TypeError: 'Email' object is not callable
2018-06-18 14:46:37,558 ERROR: Exception on /subscribe [POST] [in c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cmarsh\YewzOfficial\app\routes.py", line 22, in subscribe
    email_addr = Email(email_addr=form.email_addr.data)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\form.py", line 152, in validate
    if not field.validate(self, extra):
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "c:\users\cmarsh\appdata\local\programs\python\python36-32\lib\site-packages\wtforms\fields\core.py", line 226, in _run_validation_chain
    validator(form, self)
TypeError: 'Email' object is not callable
2018-06-18 14:47:23,406 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:48:09,733 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:48:58,488 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:49:08,533 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:49:37,159 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:49:51,945 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:50:08,303 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
2018-06-18 14:50:12,885 INFO: Yewz Startup [in C:\Users\cmarsh\YewzOfficial\app\__init__.py:38]
